---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/lf/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp .htaccess admin.php index.php item-new.php login.php logout.php $DEPLOYPATH
