<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/schema-migrations.php'; ensure_category_schema(db()); require_admin(); $message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='settings'){
  $hotelName=trim($_POST['hotel_name']??'');$contactEmail=trim($_POST['contact_email']??'');$retentionDays=(int)($_POST['retention_days']??0);
  if($hotelName===''||$retentionDays<1||($contactEmail!==''&&!filter_var($contactEmail,FILTER_VALIDATE_EMAIL)))$error='Genel ayarlardaki zorunlu alanları ve e-posta adresini kontrol edin.';
  else{foreach(['hotel_name'=>$hotelName,'retention_days'=>(string)$retentionDays,'contact_email'=>$contactEmail] as $key=>$value){$s=db()->prepare('REPLACE INTO settings (setting_key,setting_value) VALUES (?,?)');$s->execute([$key,$value]);}$message='Ayarlar kaydedildi.';}
 }
 $tables=['location'=>['location_definitions','Yer'],'department'=>['department_definitions','Departman'],'storage'=>['storage_definitions','Depo']];
 foreach($tables as $prefix=>[$table,$label]){
  if($action===$prefix.'_add'){$name=trim($_POST[$prefix.'_name']??'');if($name==='')$error="$label adı boş bırakılamaz.";else try{$order=(int)db()->query("SELECT COALESCE(MAX(sort_order),0)+1 FROM $table")->fetchColumn();$s=db()->prepare("INSERT INTO $table (name,sort_order) VALUES (?,?)");$s->execute([$name,$order]);$message="$label tanımı eklendi.";}catch(PDOException $e){$error="Bu $label zaten tanımlı.";}}
  if($action===$prefix.'_delete'){$s=db()->prepare("DELETE FROM $table WHERE id=?");$s->execute([(int)($_POST[$prefix.'_id']??0)]);$message="$label tanımı silindi.";}
  if($action===$prefix.'_edit'){$id=(int)($_POST[$prefix.'_id']??0);$name=trim($_POST[$prefix.'_name']??'');if(!$id||$name==='')$error="$label adı boş bırakılamaz.";else try{$s=db()->prepare("UPDATE $table SET name=? WHERE id=?");$s->execute([$name,$id]);$message="$label tanımı güncellendi.";}catch(PDOException $e){$error="Bu $label zaten tanımlı.";}}
 }
 if($action==='category_add'){$name=trim($_POST['category_name']??'');if($name==='')$error='Kategori adı boş bırakılamaz.';else try{$order=(int)db()->query('SELECT COALESCE(MAX(sort_order),0)+1 FROM category_definitions')->fetchColumn();$s=db()->prepare('INSERT INTO category_definitions (name,sort_order) VALUES (?,?)');$s->execute([$name,$order]);$message='Kategori eklendi.';}catch(PDOException $e){$error='Bu kategori zaten tanımlı.';}}
 if($action==='category_delete'){$id=(int)($_POST['category_id']??0);$usage=db()->prepare('SELECT (SELECT COUNT(*) FROM items WHERE category_id=?) + (SELECT COUNT(*) FROM item_definitions WHERE category_id=?)');$usage->execute([$id,$id]);if((int)$usage->fetchColumn()>0)$error='Bu kategori eşya kayıtlarında kullanıldığı için silinemez.';else{$s=db()->prepare('DELETE FROM category_definitions WHERE id=?');$s->execute([$id]);$message='Kategori silindi.';}}
 if($action==='category_edit'){$id=(int)($_POST['category_id']??0);$name=trim($_POST['category_name']??'');if(!$id||$name==='')$error='Kategori adı boş bırakılamaz.';else try{db()->beginTransaction();$s=db()->prepare('UPDATE category_definitions SET name=? WHERE id=?');$s->execute([$name,$id]);$s=db()->prepare('UPDATE items SET category=? WHERE category_id=?');$s->execute([$name,$id]);$s=db()->prepare('UPDATE item_definitions SET category=? WHERE category_id=?');$s->execute([$name,$id]);db()->commit();$message='Kategori ve bağlı eşya tanımları güncellendi.';}catch(PDOException $e){if(db()->inTransaction())db()->rollBack();$error='Bu kategori zaten tanımlı.';}}
 if($action==='item_definition_add'){$categoryId=(int)($_POST['item_category_id']??0);$name=trim($_POST['item_name']??'');$categoryStmt=db()->prepare('SELECT name FROM category_definitions WHERE id=? AND active=1');$categoryStmt->execute([$categoryId]);$category=$categoryStmt->fetchColumn();if(!$category||!$name)$error='Kategori ve eşya adı zorunludur.';else try{$order=(int)db()->query('SELECT COALESCE(MAX(sort_order),0)+1 FROM item_definitions')->fetchColumn();$s=db()->prepare('INSERT INTO item_definitions (category_id,category,name,sort_order) VALUES (?,?,?,?)');$s->execute([$categoryId,$category,$name,$order]);$message='Eşya tanımı eklendi.';}catch(PDOException $e){$error='Bu kategori altında aynı eşya zaten tanımlı.';}}
 if($action==='item_definition_delete'){$s=db()->prepare('DELETE FROM item_definitions WHERE id=?');$s->execute([(int)($_POST['item_definition_id']??0)]);$message='Eşya tanımı silindi.';}
 if($action==='item_definition_edit'){$id=(int)($_POST['item_definition_id']??0);$categoryId=(int)($_POST['item_category_id']??0);$name=trim($_POST['item_name']??'');$categoryStmt=db()->prepare('SELECT name FROM category_definitions WHERE id=? AND active=1');$categoryStmt->execute([$categoryId]);$category=$categoryStmt->fetchColumn();if(!$id||!$category||!$name)$error='Kategori ve eşya adı zorunludur.';else try{$s=db()->prepare('UPDATE item_definitions SET category_id=?,category=?,name=? WHERE id=?');$s->execute([$categoryId,$category,$name,$id]);$message='Eşya tanımı güncellendi.';}catch(PDOException $e){$error='Bu kategori altında aynı eşya zaten tanımlı.';}}
 if($action==='user'){$name=trim($_POST['name']??'');$email=trim(strtolower($_POST['email']??''));$password=$_POST['password']??'';$role=in_array($_POST['role']??'', ['Admin','User'],true)?$_POST['role']:'User';if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<6)$error='Kullanıcı bilgilerini kontrol edin.';else{$check=db()->prepare('SELECT id FROM users WHERE LOWER(email)=LOWER(?) LIMIT 1');$check->execute([$email]);if($check->fetch())$error='Bu e-posta adresi zaten kullanılıyor. Aynı e-posta ile ikinci kullanıcı oluşturulamaz.';else try{$s=db()->prepare('INSERT INTO users (name,email,password_hash,role,active) VALUES (?,?,?,?,1)');$s->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role]);$message='Kullanıcı oluşturuldu.';}catch(PDOException $e){$error='Bu e-posta adresi zaten kullanılıyor. Aynı e-posta ile ikinci kullanıcı oluşturulamaz.';}}}
}
$settings=[];foreach(db()->query('SELECT setting_key,setting_value FROM settings') as $r)$settings[$r['setting_key']]=$r['setting_value'];
$locations=db()->query('SELECT id,name FROM location_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$departments=db()->query('SELECT id,name FROM department_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$storages=db()->query('SELECT id,name FROM storage_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$categories=db()->query('SELECT id,name FROM category_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$itemDefinitions=db()->query('SELECT id,category_id,category,name FROM item_definitions WHERE active=1 ORDER BY category,sort_order,name')->fetchAll();$users=db()->query('SELECT id,name,email,role,active FROM users ORDER BY id')->fetchAll();
$profileStmt=db()->prepare('SELECT setting_value FROM settings WHERE setting_key=?');$profileStmt->execute(['profile_'.(int)$_SESSION['user']['id']]);$profile=json_decode((string)$profileStmt->fetchColumn(),true)?:[];$avatar=$profile['avatar']??'';
function definition_list(array $rows,string $prefix,string $confirm):void{foreach($rows as $row){?><div><span><?=e($row['name'])?></span><div class="row-actions"><form method="post" onsubmit="return editDefinition(this,'<?=e($row['name'])?>')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$prefix?>_edit"><input type="hidden" name="<?=$prefix?>_id" value="<?=(int)$row['id']?>"><input type="hidden" name="<?=$prefix?>_name"><button class="edit-button">Düzenle</button></form><form method="post" onsubmit="return confirm('<?=e($confirm)?>')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$prefix?>_delete"><input type="hidden" name="<?=$prefix?>_id" value="<?=(int)$row['id']?>"><button class="delete-button">Sil</button></form></div></div><?php }}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ayarlar | <?=APP_NAME?></title><link rel="icon" href="<?=url('assets/favicon.png')?>"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/item-new.css')?>"><link rel="stylesheet" href="<?=url('assets/entry.css')?>"><link rel="stylesheet" href="<?=url('assets/required.css')?>"><link rel="stylesheet" href="<?=url('assets/home-link.css')?>"><link rel="stylesheet" href="<?=url('assets/admin.css')?>"><link rel="stylesheet" href="<?=url('assets/admin-edit.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/fonts/fonts.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/icon/icomoon/style.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/css/bootstrap.min.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/css/styles.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce-lf.css')?>"><link rel="stylesheet" href="<?=url('assets/vuexy-inspired.css')?>"><link rel="stylesheet" href="<?=url('assets/dashboard-header.css')?>"><link rel="stylesheet" href="<?=url('assets/green-buttons.css?v=20260712-3')?>"><script src="<?=url('assets/theme.js?v=20260712-2')?>"></script></head><body class="admin-page">
<header class="app-header">
  <div class="header-top">
    <a class="brand brand-back-link" href="<?=url('index.php')?>" title="Ana sayfa"><img class="brand-logo" style="display:block!important;width:38px!important;height:38px!important;object-fit:contain!important" src="<?=url('assets/kirpisoftware-logo-transparent-v2.png')?>" alt="Kirpisoft"><span><b>Lost &amp; Found</b></span></a>
    <div class="header-tools">
      <button type="button" title="Arama" aria-label="Arama">⌕</button><button type="button" title="Dil">TR</button><button id="theme-toggle" type="button" title="Gece görünümüne geç" aria-label="Görünümü değiştir"><span class="theme-icon">☼</span></button>
      <div class="account-menu"><button id="account-toggle" class="account-toggle" type="button" aria-expanded="false"><span class="user-avatar"><?php if($avatar):?><img src="<?=url($avatar)?>" alt="Profil"><?php else:?><?=e(mb_strtoupper(mb_substr($_SESSION['user']['name'],0,1)))?><?php endif?></span><span class="user-name"><?=e($_SESSION['user']['name'])?><small><?=e($_SESSION['user']['role'])?></small></span><span class="account-chevron">⌄</span></button>
        <div id="account-dropdown" class="account-dropdown"><div class="account-card-head"><span class="user-avatar large"><?php if($avatar):?><img src="<?=url($avatar)?>" alt="Profil"><?php else:?><?=e(mb_strtoupper(mb_substr($_SESSION['user']['name'],0,1)))?><?php endif?></span><span><?=e($_SESSION['user']['name'])?><small><?=e($_SESSION['user']['role'])?></small></span></div><a href="<?=url('profile.php')?>"><span>♙</span> Profilim</a><a href="<?=url('admin.php')?>"><span>⚙</span> Ayarlar</a><a class="dropdown-logout" href="<?=url('logout.php')?>">Çıkış <span>↪</span></a></div>
      </div>
    </div>
  </div>
  <nav class="main-nav">
    <a href="<?=url('index.php')?>"><span>⌂</span> Ana Sayfa</a>
    <a href="<?=url('index.php')?>"><span>▣</span> Bulunan Eşyalar</a>
    <a href="<?=url('item-new.php')?>"><span>＋</span> Eşya Ekle</a>
    <a href="#"><span>◎</span> Talepler</a><a href="#"><span>⇄</span> Eşleşmeler</a>
    <a href="#"><span>▥</span> Teslimatlar</a><a href="#"><span>▤</span> Raporlar</a>
    <div class="settings-nav-menu">
      <a class="active" id="settings-nav-toggle" href="#genel" aria-haspopup="true" aria-expanded="false"><span>⚙</span> Ayarlar <span class="settings-nav-chevron">⌄</span></a>
          <div class="settings-nav-dropdown" id="settings-nav-dropdown">
        <a href="#genel"><span>⚙</span> Genel</a><a href="#yerler"><span>⌖</span> Bulunduğu yerler</a><a href="#departmanlar"><span>▦</span> Departmanlar</a><a href="#depolar"><span>▣</span> Depolar</a><a href="#kategoriler"><span>◆</span> Kategoriler</a><a href="#esyalar"><span>◆</span> Eşyalar</a><a href="#kullanicilar"><span>♙</span> Kullanıcılar</a>
      </div>
    </div>
  </nav>
</header>
<script defer src="<?=url('assets/admin-menu.js')?>"></script>
<main class="container entry-container admin-container"><div class="entry-title"><h1>Yazılım ayarları</h1><p>Tüm tanımları ve kullanıcı yetkilerini tek ekrandan yönetin.</p></div>
<?php if($message):?><div class="success"><?=e($message)?></div><?php endif?><?php if($error):?><div class="alert"><?=e($error)?></div><?php endif?>
<form id="genel" class="entry-panel form-grid settings-section admin-form-panel" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><label>Otel adı<input name="hotel_name" value="<?=e($settings['hotel_name']??'Sofitel Istanbul Taksim')?>" required></label><label>İletişim e-postası<input type="email" name="contact_email" value="<?=e($settings['contact_email']??'')?>"></label><label>Saklama süresi (gün)<input type="number" min="1" name="retention_days" value="<?=e($settings['retention_days']??90)?>" required></label><div class="wide entry-actions admin-entry-actions"><button class="save-button">Kaydet</button></div></form>
<?php foreach([['yerler','Bulunduğu yer tanımları','location','Yeni yer adı',$locations],['departmanlar','Bulan departman tanımları','department','Yeni departman adı',$departments],['depolar','Depo tanımları','storage','Yeni depo adı',$storages]] as [$id,$title,$prefix,$placeholder,$rows]):?><section id="<?=$id?>" class="title-row admin-subtitle"><div><h1><?=$title?></h1></div></section><form class="panel location-add" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$prefix?>_add"><input name="<?=$prefix?>_name" placeholder="<?=$placeholder?>" required><button class="primary">Ekle</button></form><section class="panel location-list"><?php definition_list($rows,$prefix,'Bu tanım silinsin mi?')?></section><?php endforeach?>
<section id="kategoriler" class="title-row admin-subtitle"><div><h1>Kategoriler</h1><p>Eşya kategorilerini ekleyin, düzenleyin ve yönetin.</p></div></section>
<form class="panel location-add" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="category_add"><input name="category_name" placeholder="Yeni kategori adı" required><button class="primary">Kategori ekle</button></form>
<section class="panel location-list"><?php definition_list($categories,'category','Bu kategori silinsin mi? Kullanımdaki kategoriler silinemez.')?></section>
<section id="esyalar" class="title-row admin-subtitle"><div><h1>Eşya tanımları</h1><p>Her eşya tanımını bir kategoriyle eşleştirerek yönetin.</p></div></section>
<form class="panel item-definition-add" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item_definition_add"><select name="item_category_id" required><option value="">Kategori seçiniz</option><?php foreach($categories as $category):?><option value="<?=(int)$category['id']?>"><?=e($category['name'])?></option><?php endforeach?></select><input name="item_name" placeholder="Eşya adı" required><button class="primary">Eşya ekle</button></form>
<section class="panel location-list item-definition-list"><?php foreach($itemDefinitions as $d):?><div><span><b><?=e($d['category'])?></b> – <?=e($d['name'])?></span><div class="row-actions"><form method="post" class="item-definition-edit-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item_definition_edit"><input type="hidden" name="item_definition_id" value="<?=(int)$d['id']?>"><select name="item_category_id" aria-label="Kategori"><?php foreach($categories as $category):?><option value="<?=(int)$category['id']?>" <?=((int)$category['id']===(int)$d['category_id'])?'selected':''?>><?=e($category['name'])?></option><?php endforeach?></select><input name="item_name" value="<?=e($d['name'])?>" aria-label="Eşya adı" required><button class="edit-button">Güncelle</button></form><form method="post" onsubmit="return confirm('Bu eşya tanımı silinsin mi?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item_definition_delete"><input type="hidden" name="item_definition_id" value="<?=(int)$d['id']?>"><button class="delete-button">Sil</button></form></div></div><?php endforeach?></section>
<section id="kullanicilar" class="title-row admin-subtitle"><div><h1>Kullanıcılar</h1><p>Admin ayarları yönetir; User uygulamayı kullanır.</p></div></section><form class="entry-panel form-grid admin-form-panel" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="user"><label>Ad soyad<input name="name" required></label><label>E-posta<input type="email" name="email" required></label><label>Şifre<input type="password" name="password" minlength="6" required></label><label>Rol<select name="role" required><option>User</option><option>Admin</option></select></label><div class="wide entry-actions admin-entry-actions"><button class="save-button">Kullanıcı ekle</button></div></form><section class="panel users-panel"><table><thead><tr><th>Ad soyad</th><th>E-posta</th><th>Rol</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['name'])?></td><td><?=e($u['email'])?></td><td><span class="role-badge"><?=e($u['role'])?></span></td><td><?=$u['active']?'Aktif':'Pasif'?></td><td><?php if($u['role']==='User'):?><a class="edit-button user-edit-link" href="<?=url('user-edit.php?id='.(int)$u['id'])?>">Düzenle / Şifre</a><?php else:?><span class="admin-protected">Yönetici</span><?php endif?></td></tr><?php endforeach?></tbody></table></section>
</main><script>function editDefinition(form,current){const value=prompt('Yeni adı girin:',current);if(value===null||!value.trim())return false;form.querySelector('input[name$="_name"]').value=value.trim();return true}function editItem(form,category,name){const newCategory=prompt('Kategori:',category);if(newCategory===null)return false;const newName=prompt('Eşya adı:',name);if(newName===null||!newCategory.trim()||!newName.trim())return false;form.item_category.value=newCategory.trim();form.item_name.value=newName.trim();return true}const root=document.documentElement,themeButton=document.getElementById('theme-toggle'),themeIcon=themeButton.querySelector('.theme-icon');function setTheme(theme){root.dataset.theme=theme;localStorage.setItem('lf-theme',theme);const dark=theme==='dark';themeIcon.textContent=dark?'☾':'☼';themeButton.title=dark?'Gündüz görünümüne geç':'Gece görünümüne geç'}setTheme(localStorage.getItem('lf-theme')||'light');themeButton.addEventListener('click',()=>setTheme(root.dataset.theme==='dark'?'light':'dark'));const accountButton=document.getElementById('account-toggle'),dropdown=document.getElementById('account-dropdown');accountButton.addEventListener('click',event=>{event.stopPropagation();const open=dropdown.classList.toggle('open');accountButton.setAttribute('aria-expanded',open)});document.addEventListener('click',event=>{if(!dropdown.contains(event.target)){dropdown.classList.remove('open');accountButton.setAttribute('aria-expanded','false')}});</script><script src="<?=url('assets/required.js')?>"></script></body></html>
