<?php
require __DIR__ . '/config.php'; require_login();
$q = trim($_GET['q'] ?? ''); $status = $_GET['status'] ?? '';
$sql = 'SELECT * FROM items WHERE 1=1'; $params = [];
if ($q !== '') { $sql .= ' AND (item_no LIKE ? OR name LIKE ? OR location LIKE ? OR category LIKE ?)'; $like = "%$q%"; $params = [$like,$like,$like,$like]; }
if ($status !== '') { $sql .= ' AND status = ?'; $params[] = $status; }
$sql .= ' ORDER BY found_at DESC, id DESC LIMIT 100';
$stmt = db()->prepare($sql); $stmt->execute($params); $items = $stmt->fetchAll();
$counts = db()->query("SELECT COUNT(*) total, SUM(status='Depoda') storage, SUM(status='Eşleşme bekliyor') waiting, SUM(status='Teslim edildi') delivered FROM items")->fetch();
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bulunan Eşyalar | <?= APP_NAME ?></title><link rel="icon" type="image/png" href="<?= url('assets/favicon.png') ?>"><link rel="stylesheet" href="<?= url('assets/style.css') ?>"></head><body>
<header><div class="brand"><span class="brand-mark">K</span><span>KRP <b>Lost & Found</b></span></div><nav><a class="active" href="<?= url('index.php') ?>">Eşyalar</a><a href="#">Talepler</a><a href="#">Raporlar</a><?php if(is_admin()): ?><a href="<?= url('admin.php') ?>">Ayarlar</a><?php endif ?></nav><div class="user"><span><?= e($_SESSION['user']['name']) ?><small><?= e($_SESSION['user']['role']) ?></small></span><a href="<?= url('logout.php') ?>">Çıkış</a></div></header>
<main class="container"><section class="title-row"><div><p class="eyebrow">ENVANTER YÖNETİMİ</p><h1>Bulunan eşyalar</h1><p>Tüm kayıtları tek ekrandan takip edin ve yönetin.</p></div><a class="primary button" href="<?= url('item-new.php') ?>">+ Yeni eşya kaydı</a></section>
<section class="stats"><article><span>Toplam kayıt</span><strong><?= (int)($counts['total'] ?? 0) ?></strong></article><article><span>Depodaki</span><strong><?= (int)($counts['storage'] ?? 0) ?></strong></article><article><span>Eşleşme bekleyen</span><strong><?= (int)($counts['waiting'] ?? 0) ?></strong></article><article><span>Teslim edilen</span><strong><?= (int)($counts['delivered'] ?? 0) ?></strong></article></section>
<section class="panel"><form class="filters"><input name="q" value="<?= e($q) ?>" placeholder="Eşya no, isim, kategori veya yer ara"><select name="status"><option value="">Tüm durumlar</option><?php foreach(['Depoda','Eşleşme bekliyor','Teslim edildi','Kargolandı','Tasfiye edildi'] as $s): ?><option <?= $status===$s?'selected':'' ?>><?= e($s) ?></option><?php endforeach ?></select><button type="submit">Ara</button></form><div class="table-wrap"><table><thead><tr><th>Eşya no</th><th>Bulunduğu tarih</th><th>Yer</th><th>Kategori</th><th>Eşya</th><th>Renk</th><th>Depo</th><th>Durum</th><th>Kaydeden</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><b class="item-no"><?= e($item['item_no']) ?></b></td><td><?= e(date('d.m.Y',strtotime($item['found_at']))) ?></td><td><?= e($item['location']) ?></td><td><?= e($item['category']) ?></td><td><strong><?= e($item['name']) ?></strong><small><?= e($item['details']) ?></small></td><td><?= e($item['color']) ?></td><td><?= e($item['storage_location']) ?></td><td><span class="badge"><?= e($item['status']) ?></span></td><td><?= e($item['recorded_by']) ?></td></tr><?php endforeach ?><?php if(!$items): ?><tr><td colspan="9" class="empty">Kayıt bulunamadı.</td></tr><?php endif ?></tbody></table></div></section></main></body></html>
