<?php
require __DIR__.'/config.php'; require_login(); $error='';
$locations=db()->query('SELECT name FROM location_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();
$departments=db()->query('SELECT name FROM department_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();
$storages=db()->query('SELECT name FROM storage_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();
$itemDefinitions=db()->query('SELECT id,category,name FROM item_definitions WHERE active=1 ORDER BY sort_order,category,name')->fetchAll();
$draftNo=$_POST['item_no']??('KRP-'.date('ymd').'-'.str_pad((string)random_int(1,9999),4,'0',STR_PAD_LEFT));
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 foreach(['found_at','location','found_department','item_definition','storage_location'] as $key) if(trim($_POST[$key]??'')==='') $error='Zorunlu alanları doldurun.';
 $selectedDefinition=null;
 if(!$error){$s=db()->prepare('SELECT category,name FROM item_definitions WHERE id=? AND active=1');$s->execute([(int)$_POST['item_definition']]);$selectedDefinition=$s->fetch();if(!$selectedDefinition)$error='Geçerli bir eşya seçin.';}
 if(!$error){
  $stmt=db()->prepare('INSERT INTO items (item_no,found_at,location,found_department,found_by,quantity,category,name,brand,color,details,storage_location,status,recorded_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
  $stmt->execute([$draftNo,$_POST['found_at'],trim($_POST['location']),trim($_POST['found_department']),trim($_POST['found_by']??''),max(1,(int)($_POST['quantity']??1)),$selectedDefinition['category'],$selectedDefinition['name'],'','',trim($_POST['details']??''),trim($_POST['storage_location']),'Depoda',$_SESSION['user']['name']]);
  redirect('index.php');
 }
}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eşya Ekle | <?=APP_NAME?></title><link rel="icon" type="image/png" href="<?=url('assets/favicon.png')?>"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/item-new.css')?>"><link rel="stylesheet" href="<?=url('assets/entry.css')?>"><link rel="stylesheet" href="<?=url('assets/required.css')?>"><link rel="stylesheet" href="<?=url('assets/home-link.css')?>"></head><body>
<header><div class="brand"><span class="brand-mark">K</span><span>KRP <b>Lost & Found</b></span></div><a class="home-link" href="<?=url('index.php')?>" title="Ana sayfa" aria-label="Ana sayfa" style="width:40px;height:40px;display:grid;place-items:center;border-radius:8px;background:#edf5ff;color:#1677ff;font-size:24px;margin-left:12px"><span aria-hidden="true">🏠</span></a></header>
<main class="container entry-container"><div class="entry-title"><h1>Eşya Ekle</h1><p>Bulunan eşyayı hızlıca kaydedin.</p></div><?php if($error):?><div class="alert"><?=e($error)?></div><?php endif?>
<form id="item-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><section class="entry-panel">
<div class="entry-toolbar"><label class="tool-button blue" title="Fotoğraf ekle">📷<input type="file" name="photo" accept="image/*"></label><label class="tool-button blue" title="Dosya yükle">⬆<input type="file" name="attachment"></label><button class="tool-button cyan" type="button" title="Önizleme">◉</button></div>
<div class="entry-grid">
<label>Eşya *<div class="search-select" data-search-select><input type="hidden" name="item_definition" value="<?=e($_POST['item_definition']??'')?>" required><button class="search-select-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><span>Seçiniz</span><i></i></button><div class="search-select-menu"><input class="search-select-input" type="search" placeholder="Eşya ara..." autocomplete="off"><div class="search-select-options" role="listbox"><?php foreach($itemDefinitions as $d):$label=$d['category'].' - '.$d['name'];?><button type="button" role="option" data-value="<?=(int)$d['id']?>" data-label="<?=e($label)?>"><?=e($label)?></button><?php endforeach?><p class="search-select-empty">Sonuç bulunamadı.</p></div></div></div></label>
<label>Oda no / Bulunduğu yer *<select name="location" required><option value="">Yer seçiniz</option><?php foreach($locations as $v):?><option <?=($_POST['location']??'')===$v['name']?'selected':''?>><?=e($v['name'])?></option><?php endforeach?></select></label>
<label>Bulunduğu tarih *<input type="date" name="found_at" value="<?=e($_POST['found_at']??date('Y-m-d'))?>" required></label>
<label>Bulan departman *<select name="found_department" required><option value="">Departman seçiniz</option><?php foreach($departments as $v):?><option <?=($_POST['found_department']??'')===$v['name']?'selected':''?>><?=e($v['name'])?></option><?php endforeach?></select></label>
<label>Bulan bilgisi<input name="found_by" value="<?=e($_POST['found_by']??'')?>" placeholder="Seçin veya yenisini girin"></label>
<label>Kayıt no<input name="item_no" value="<?=e($draftNo)?>" readonly></label><label>Miktar<input type="number" name="quantity" min="1" value="<?=e($_POST['quantity']??'1')?>"></label>
<label>Depo *<select name="storage_location" required><option value="">Depo seçiniz</option><?php foreach($storages as $v):?><option <?=($_POST['storage_location']??'')===$v['name']?'selected':''?>><?=e($v['name'])?></option><?php endforeach?></select></label>
<label class="details-field">Açıklama<textarea name="details" rows="1" placeholder="Eşyanın ayırt edici özellikleri"><?=e($_POST['details']??'')?></textarea></label>
</div></section><div class="entry-actions"><button class="new-button" type="reset">▣ Yeni eşya</button><button class="save-button" type="submit">▣ Kaydet</button><a href="<?=url('index.php')?>">İptal</a></div></form></main>
<script>document.querySelectorAll('[data-search-select]').forEach(select=>{const hidden=select.querySelector('input[type=hidden]'),trigger=select.querySelector('.search-select-trigger'),caption=trigger.querySelector('span'),search=select.querySelector('.search-select-input'),options=[...select.querySelectorAll('[role=option]')],empty=select.querySelector('.search-select-empty');const selected=options.find(o=>o.dataset.value===hidden.value);if(selected)caption.textContent=selected.dataset.label;const close=()=>{select.classList.remove('open');trigger.setAttribute('aria-expanded','false')};trigger.addEventListener('click',()=>{const opening=!select.classList.contains('open');select.classList.toggle('open',opening);trigger.setAttribute('aria-expanded',String(opening));if(opening){search.value='';options.forEach(o=>o.hidden=false);empty.hidden=true;search.focus()}});search.addEventListener('input',()=>{const term=search.value.toLocaleLowerCase('tr-TR').trim();let visible=0;options.forEach(o=>{o.hidden=!o.dataset.label.toLocaleLowerCase('tr-TR').includes(term);if(!o.hidden)visible++});empty.hidden=visible!==0});options.forEach(o=>o.addEventListener('click',()=>{hidden.value=o.dataset.value;caption.textContent=o.dataset.label;options.forEach(x=>x.setAttribute('aria-selected',String(x===o)));close()}));document.addEventListener('click',e=>{if(!select.contains(e.target))close()})});</script><script src="<?=url('assets/required.js')?>"></script></body></html>
