<?php
require __DIR__ . '/config.php';
require_login();
if (!function_exists('date_display')) {
    function date_display(?string $value): string {
        $value = trim((string)$value);
        if ($value === '') return '';
        try { return (new DateTimeImmutable($value, new DateTimeZone('Europe/Istanbul')))->format('d.m.Y'); }
        catch (Throwable) { return ''; }
    }
}
$id = (int)($_GET['id'] ?? 0);
$stmt = db()->prepare('SELECT * FROM items WHERE id=?');
$stmt->execute([$id]);
$item = $stmt->fetch();
if (!$item) { http_response_code(404); exit('Kayıt bulunamadı.'); }
$foundDate = date_display($item['found_at']);
$printDate = (new DateTimeImmutable('today', new DateTimeZone('Europe/Istanbul')))->format('d.m.Y');
function label_text(?string $value): string { return e(trim((string)$value) ?: '—'); }
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Etiket | <?=e($item['item_no'])?></title><style>.label-head{position:relative}.title{position:absolute!important;left:72mm!important;right:0!important;top:0!important;bottom:0!important;padding:0!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;text-align:center!important;transform:none!important}.title span:first-child{white-space:nowrap;font-size:11pt}.brand{position:relative;z-index:1;background:none!important}.brand img{display:block!important;width:55mm!important;height:16mm!important;max-width:55mm!important;object-fit:contain!important}</style><script>document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.brand img').forEach(img=>{img.src='<?=url('assets/sofitel-logo.jpg')?>';img.alt='Sofitel İstanbul Taksim'}));</script>
<style>@page{size:A4 portrait;margin:11mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#000;background:#f5f5f5}.toolbar{max-width:190mm;margin:14px auto;display:flex;gap:10px}.toolbar button,.toolbar a{padding:10px 16px;border:0;border-radius:6px;background:#f97316;color:#fff;font-weight:700;text-decoration:none;cursor:pointer}.sheet{width:190mm;margin:0 auto;background:#fff;padding:0}.label-row{display:flex;align-items:center;gap:5mm;height:130mm;padding:4mm 0;border-bottom:1px solid #999}.label-row:last-child{border:0}.label-main{width:150mm;height:112mm;border:1.5px solid #000;display:flex;flex-direction:column;overflow:hidden}.label-head{height:25mm;flex:0 0 25mm;display:flex;border-bottom:1px solid #bbb}.brand{width:72mm;display:flex;align-items:center;padding:5mm}.brand img{width:30mm;height:15mm;object-fit:contain}.brand strong{display:none}.title{flex:1;text-align:right;padding:4mm 5mm 1mm;font-weight:700;font-size:10pt}.title span{display:block}.label-no{color:#e11;font-size:13pt}.line{display:grid;grid-template-columns:37mm 1fr;min-height:12mm;flex:0 0 12mm;border-bottom:1px solid #c8c8c8}.line:last-child{border-bottom:0}.line .caption{padding:2mm 1mm;font-size:7pt;font-weight:700;border-right:1px solid #ddd}.line .caption em{display:block;font-size:6pt;font-weight:400}.line .value{padding:3mm 4mm;font-size:9pt;font-weight:700}.line.large{min-height:18mm;flex-basis:18mm}.line.delivery .value{display:grid;grid-template-columns:1fr 1fr;gap:5mm;font-size:8pt}.label-stub{width:35mm;height:112mm;border:1px solid #999;display:flex;align-items:center;justify-content:center;position:relative}.label-stub .stub-content{writing-mode:vertical-rl;text-orientation:mixed;text-align:center;font-weight:700;font-size:14pt;line-height:1.7}.label-stub small{font-size:9pt;font-weight:400}@media print{body{background:#fff}.toolbar{display:none}.sheet{width:190mm;margin:0}.label-row{break-inside:avoid}}</style></head><body>
<div class="toolbar"><button type="button" onclick="window.print()">Etiketi Yazdır</button><a href="<?=url('item-edit.php?id='.$id)?>">Karta dön</a></div><main class="sheet">
<?php for($copy=0;$copy<2;$copy++):?><section class="label-row"><article class="label-main"><header class="label-head"><div class="brand"><img src="<?=url('assets/kirpisoftware-logo-transparent-v2.png')?>" alt="Lost & Found"><strong>Lost &amp; Found</strong></div><div class="title"><span>KAYBOLAN VE BULUNAN EŞYA FORMU</span><span>LOST AND FOUND FORM</span><span class="label-no">No: <?=e($item['item_no'])?><?=trim((string)$item['serial_no'])!==''?' ('.e($item['serial_no']).')':''?></span><span>Tarih / Date: <?=$printDate?></span></div></header><div class="line large"><div class="caption">Eşya<em>Item</em></div><div class="value"><?=label_text($item['category'].' - '.$item['name'])?></div></div><div class="line"><div class="caption">Bulunduğu Tarih<em>Date Found</em></div><div class="value"><?=label_text($foundDate)?></div></div><div class="line"><div class="caption">Bulunduğu Yer<em>Place Found</em></div><div class="value"><?=label_text($item['location'])?></div></div><div class="line"><div class="caption">Bulan Adı<em>Found By</em></div><div class="value"><?=label_text($item['found_by'])?></div></div><div class="line"><div class="caption">Kayıp Eden<em>Who Lost</em></div><div class="value"></div></div><div class="line delivery"><div class="caption">Depo Adı<em>Store Name</em></div><div class="value"><span><?=label_text($item['storage_location'])?></span><span>Tarih / İmza: <?=$printDate?></span></div></div></article><aside class="label-stub"><div class="stub-content"><?=label_text($item['serial_no'] ?: $item['item_no'])?><br><small><?=label_text($item['found_by'])?></small></div></aside></section><?php endfor?>
</main></body></html>
