<?php
require __DIR__.'/config.php'; require_once __DIR__.'/transfer-schema.php'; require_record_manager(); $pdo=db(); ensure_transfer_batch($pdo); $error='';
$storages=$pdo->query('SELECT name FROM storage_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll(PDO::FETCH_COLUMN);
$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['item_ids']??[])),fn($id)=>$id>0)));
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $target=trim($_POST['to_storage']??''); $notes=trim($_POST['notes']??'');
 if(!$ids)$error='En az bir eşya seçin.';
 elseif(!in_array($target,$storages,true))$error='Geçerli bir hedef depo seçin.';
 elseif(mb_strlen($notes)>512)$error='Not en fazla 512 karakter olabilir.';
 if(!$error)try{
 $pdo->beginTransaction();
 $q=$pdo->prepare('SELECT id,storage_location FROM items WHERE id IN ('.implode(',',array_fill(0,count($ids),'?')).')'.($pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':''));
 $q->execute($ids);$selected=$q->fetchAll();
 if(count($selected)!==count($ids))throw new RuntimeException('Bir eşya bulunamadı. Seçimi yenileyin.');
 foreach($selected as $item)if($item['storage_location']===$target)throw new RuntimeException('Seçilen eşyalardan biri zaten hedef depoda. Seçimi kontrol edin.');
 $batch=bin2hex(random_bytes(16));$now=(new DateTimeImmutable('now',new DateTimeZone('Europe/Istanbul')))->format('Y-m-d H:i:s');
 $u=$pdo->prepare('UPDATE items SET storage_location=?,updated_by=?,updated_at=? WHERE id=?');
 $t=$pdo->prepare('INSERT INTO storage_transfers(item_id,from_storage,to_storage,notes,transferred_by,transferred_at,batch_id) VALUES(?,?,?,?,?,?,?)');
 foreach($selected as $item){$u->execute([$target,$_SESSION['user']['name'],$now,$item['id']]);$t->execute([$item['id'],$item['storage_location'],$target,$notes,$_SESSION['user']['name'],$now,$batch]);}
 $printId=(int)$pdo->lastInsertId();$pdo->commit();redirect('transfer.php?transfer_id='.$printId);
 }catch(Throwable $ex){if($pdo->inTransaction())$pdo->rollBack();$error=$ex instanceof RuntimeException?$ex->getMessage():'Transfer kaydedilemedi.';}
}
$items=$pdo->query('SELECT id,item_no,serial_no,category,name,quantity,storage_location FROM items ORDER BY id DESC')->fetchAll();
$history=$pdo->query('SELECT t.*,i.item_no FROM storage_transfers t LEFT JOIN items i ON i.id=t.item_id ORDER BY t.id DESC LIMIT 100')->fetchAll();
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Depo Transferi</title><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/vuexy-inspired.css')?>"><style>.selection{max-height:440px;overflow:auto}.selection input{width:auto}.selection table{min-width:650px}.search{padding:20px;display:flex;gap:20px;align-items:center}.search input{max-width:480px}.picked{background:#f0edff}</style></head><body><header><a class="brand" href="<?=url('index.php')?>"><b>Lost &amp; Found</b></a><nav><a href="<?=url('index.php')?>">Ana Sayfa</a><a class="active" href="<?=url('transfer.php')?>">Depo Transferi</a></nav></header><main class="container"><div class="title-row"><div><h1>Depo Transferi</h1><p>Eşyaları seçin ve birlikte hedef depoya aktarın.</p></div></div>
<?php if($error):?><div class="alert"><?=e($error)?></div><?php endif?>
<?php if(isset($_GET['transfer_id'])):?><div class="panel search">Transfer kaydedildi. <a class="button primary" target="_blank" href="<?=url('transfer-print.php?id='.(int)$_GET['transfer_id'])?>">Toplu transfer formunu yazdır</a></div><?php endif?>
<form method="post" class="panel"><input type="hidden" name="csrf" value="<?=csrf()?>"><div class="search"><input id="search" type="search" placeholder="Eşya no, seri no, eşya veya depo ara" aria-label="Eşya ara"><strong id="count"></strong></div><div class="selection"><table><thead><tr><th><input id="all" type="checkbox" aria-label="Görünen eşyaları seç"></th><th>Eşya no / Seri no</th><th>Eşya</th><th>Miktar</th><th>Mevcut depo</th></tr></thead><tbody>
<?php foreach($items as $item):?><tr data-search="<?=e(implode(' ',array_values($item)))?>"><td><input type="checkbox" name="item_ids[]" value="<?=(int)$item['id']?>" aria-label="<?=e($item['item_no'].' seç')?>" <?=in_array((int)$item['id'],$ids,true)?'checked':''?>></td><td><?=e($item['item_no'])?><small><?=e($item['serial_no'])?></small></td><td><?=e($item['category'].' / '.$item['name'])?></td><td><?=(int)$item['quantity']?></td><td><?=e($item['storage_location'])?></td></tr><?php endforeach?></tbody></table></div><div class="form-grid"><label>Hedef depo *<select name="to_storage" required><option value="">Depo seçiniz</option><?php foreach($storages as $s):?><option <?=($_POST['to_storage']??'')===$s?'selected':''?>><?=e($s)?></option><?php endforeach?></select></label><label>İşlemi yapan<input readonly value="<?=e($_SESSION['user']['name'])?>"></label><label class="wide">Transfer notu<textarea name="notes" maxlength="512" rows="3"><?=e($_POST['notes']??'')?></textarea></label><div class="wide actions"><button class="primary">Seçilenleri Transfer Et</button></div></div></form>
<section class="panel" style="margin-top:24px"><h2 style="padding:20px">Son Transferler</h2><div class="table-wrap"><table><thead><tr><th>Tarih</th><th>Eşya no</th><th>Çıkış deposu</th><th>Hedef depo</th><th>İşlemi yapan</th><th>Form</th></tr></thead><tbody><?php foreach($history as $t):?><tr><td><?=e(date('d.m.Y H:i',strtotime($t['transferred_at'])))?></td><td><?=e($t['item_no'])?></td><td><?=e($t['from_storage'])?></td><td><?=e($t['to_storage'])?></td><td><?=e($t['transferred_by'])?></td><td><a target="_blank" href="<?=url('transfer-print.php?id='.(int)$t['id'])?>">Yazdır</a></td></tr><?php endforeach?></tbody></table></div></section></main>
<script>const rows=[...document.querySelectorAll('[data-search]')],all=document.getElementById('all');function update(){document.getElementById('count').textContent=rows.filter(r=>r.querySelector('input').checked).length+' eşya seçildi';rows.forEach(r=>r.classList.toggle('picked',r.querySelector('input').checked));const visible=rows.filter(r=>!r.hidden);all.checked=visible.length>0&&visible.every(r=>r.querySelector('input').checked);all.indeterminate=!all.checked&&visible.some(r=>r.querySelector('input').checked)}rows.forEach(r=>r.querySelector('input').addEventListener('change',update));document.getElementById('search').addEventListener('input',e=>{rows.forEach(r=>r.hidden=!r.dataset.search.toLocaleLowerCase('tr').includes(e.target.value.toLocaleLowerCase('tr')));update()});all.addEventListener('change',()=>{rows.filter(r=>!r.hidden).forEach(r=>r.querySelector('input').checked=all.checked);update()});update();</script></body></html>
