<?php
require __DIR__.'/config.php';require_once __DIR__.'/transfer-schema.php';require_login();$pdo=db();ensure_transfer_batch($pdo);
$selectedIds=array_values(array_unique(array_filter(array_map('intval',(array)($_GET['transfer_ids']??[])),fn($value)=>$value>0)));
$isSelection=array_key_exists('transfer_ids',$_GET);
if($isSelection){
 if(!$selectedIds||count($selectedIds)>100){http_response_code(400);exit('1 ile 100 arasında transfer seçin.');}
 $where='t.id IN ('.implode(',',array_fill(0,count($selectedIds),'?')).')';$params=$selectedIds;
}else{
 $id=(int)($_GET['id']??0);$q=$pdo->prepare('SELECT * FROM storage_transfers WHERE id=?');$q->execute([$id]);$transfer=$q->fetch();
 if(!$transfer){http_response_code(404);exit('Transfer bulunamadı.');}
 $where=$transfer['batch_id']?'t.batch_id=?':'t.id=?';$params=[$transfer['batch_id']?:$id];
}
$q=$pdo->prepare('SELECT t.*,i.item_no,i.serial_no,i.category,i.name,i.quantity,i.found_at,i.location,i.found_by,i.recorded_by,i.color FROM storage_transfers t LEFT JOIN items i ON i.id=t.item_id WHERE '.$where.' ORDER BY t.id');
$q->execute($params);$rows=$q->fetchAll();
if(!$rows||($isSelection&&count($rows)!==count($selectedIds))){http_response_code(404);exit('Seçilen transferlerden biri bulunamadı.');}
$transfer=$rows[0];
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Depo Transfer Formu</title><style>body{font:13px Arial;color:#111;background:#eee}main{max-width:267mm;margin:20px auto;background:white;padding:15mm}h1{font-size:22px;border-bottom:2px solid #222;padding-bottom:15px}table{width:100%;border-collapse:collapse;margin:25px 0}th,td{border:1px solid #888;padding:8px;text-align:left}th{background:#eee}thead{display:table-header-group}tr{break-inside:avoid}.signatures{display:flex;justify-content:space-between;margin-top:70px;break-inside:avoid}.signatures div{width:43%;border-top:1px solid;padding-top:12px;text-align:center}.toolbar{text-align:center}button{padding:12px 24px;cursor:pointer}.notes{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid #999;padding:15px}@media print{body{background:white;margin:0}.toolbar{display:none}main{margin:0;max-width:none;padding:0}@page{size:A4 landscape;margin:15mm}}</style></head><body><div class="toolbar"><a href="<?=url('transfer.php')?>" style="display:inline-block;padding:12px 24px;color:#111">← Geri dön</a><button onclick="window.print()">Yazdır</button></div><main><h1>Lost &amp; Found — DEPO TRANSFER FORMU</h1><?php if(!$isSelection):?><p>Form no: <?=e((string)$rows[0]['id'])?> &nbsp; Tarih: <?=e(date('d.m.Y H:i',strtotime($transfer['transferred_at'])))?></p><p>Hedef depo: <strong><?=e($transfer['to_storage'])?></strong> &nbsp; İşlemi yapan: <?=e($transfer['transferred_by'])?></p><?php else:?><p>Seçilen transfer kalemleri — Formlar: <?=e(implode(', ',array_column($rows,'id')))?></p><?php endif?><p>Toplam <?=count($rows)?> eşya kaydı</p><table><thead><tr><th>Lost form no / Seri no</th><th>Bulunma tarihi</th><th>Eşyanın tanımı</th><th>Bulunan yer</th><th>Teslim eden personel</th><th>Kayıt eden</th><th>Transfer tarihi</th><th>Çıkış / Hedef depo</th><th>İşlemi yapan / Not</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=e($row['item_no'])?><br><?=e($row['serial_no'])?></td><td><?=e($row['found_at']?date('d.m.Y',strtotime($row['found_at'])):'')?></td><td><?=e($row['category'].' / '.$row['name'].($row['color']?' — '.$row['color']:''))?> (<?=(int)$row['quantity']?>)</td><td><?=e($row['location'])?></td><td><?=e($row['found_by'])?></td><td><?=e($row['recorded_by'])?></td><td><?=e(date('d.m.Y',strtotime($row['transferred_at'])))?></td><td><?=e($row['from_storage'].' → '.$row['to_storage'])?></td><td><?=e($row['transferred_by'])?><br><?=e($row['notes'])?></td></tr><?php endforeach?></tbody></table><?php if(!$isSelection):?><div class="notes">Transfer notu: <?=e($transfer['notes'])?></div><?php endif?><div class="signatures"><div><strong>Teslim Eden</strong><p>Ad Soyad / İmza / Tarih</p></div><div><strong>Teslim Alan</strong><p>Ad Soyad / İmza / Tarih</p></div></div></main></body></html>
